[custom]
ruleset=🚀 节点选择,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/ProxyGFWlist.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Other/BanADP.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🪟 微软服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/OneDrive.list
ruleset=🪟 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 国外网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Other/Proxy.list
ruleset=🚀 国外网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/Twitter.list
ruleset=🚀 国外网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/Github.list
ruleset=🚀 国外网站,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/Wikipedia.list
ruleset=🎵 国外音乐,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/Spotify.list
ruleset=🤖 人工智能,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🤖 人工智能,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 人工智能,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Other/ChatGPT.list
ruleset=🍀 谷歌服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/Google.list
ruleset=🍀 谷歌服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Other/GoogleIP.list
ruleset=🍀 谷歌服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🍀 谷歌服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/GoogleFCM.list
ruleset=🍀 谷歌服务,https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rules/ACL4SSR/Clash/Ruleset/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 便宜自动`[]🇸🇬 便宜加坡`[]🍃 便宜手动`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🔑 优质节点`select`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT

custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]🔑 优质节点`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换
custom_proxy_group=🇸🇬 加坡节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇸🇬 便宜加坡`select`!!GROUPID=!0!!(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|🇭🇰|HongKong|Hong Kong)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=🍃 便宜手动`select`!!GROUPID=!0!!.*
custom_proxy_group=♻️ 便宜自动`url-test`!!GROUPID=!0!!.*`http://www.gstatic.com/generate_204`300

custom_proxy_group=🎮 游戏平台`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🤖 人工智能`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🚀 国外网站`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🍀 谷歌服务`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🪟 微软服务`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=📲 电报消息`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🎵 国外音乐`select`[]🔑 优质节点`[]🚀 节点选择`[]🇸🇬 加坡节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🔑 优质节点`[]🐸 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🔑 优质节点`[]🐸 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT

custom_proxy_group=❤机场0检查❤`select`!!GROUPID=0!!.*
custom_proxy_group=❤机场1检查❤`select`!!GROUPID=1!!.*
custom_proxy_group=❤机场2检查❤`select`!!GROUPID=2!!.*
custom_proxy_group=❤机场3检查❤`select`!!GROUPID=3!!.*
custom_proxy_group=❤机场4检查❤`select`!!GROUPID=4!!.*

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
