[custom]
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ERROR0cai/fenliu/refs/heads/main/Direct.list

;策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]❤机场0检查❤`[]❤机场1检查❤

custom_proxy_group=❤机场0检查❤`select`!!GROUPID=0!!.*
custom_proxy_group=❤机场1检查❤`select`!!GROUPID=1!!.*
custom_proxy_group=❤机场2检查❤`select`!!GROUPID=2!!.*
custom_proxy_group=❤机场3检查❤`select`!!GROUPID=3!!.*
custom_proxy_group=❤机场4检查❤`select`!!GROUPID=4!!.*

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
